### ISSUE TITLE
Feature Request: Make JFrame Optional

### ISSUE THREAD

**Issue by aboy021** [Macroz/tangle#1]
There's a call on line 256, javax.imageio.ImageIO/read, that causes a JFrame to be created. It would be great if this weren't there.

**Comment by Macroz** [comment]
Hey, can you describe your use case further? Are you running headless somewhere and the problem appears or in your desktop? Do you suggest that there is another method that does not read the image back so that you can use it instead?

**Comment by aboy021** [comment]
It was blowing up on our build server.
The problem is that if I even load the file, without running the function, a JFrame appears.
For my use case I'm just writing out an svg.

**Comment by Macroz** [comment]
Ok, did you try [this approach](http://stackoverflow.com/questions/11740012/clojure-java-pop-up-window) with `java.awt.headless`?

I think the image loading and `BufferedImage` part is not a very important feature, so it could be removed or provided just as an example.

**Comment by aboy021** [comment]
For the time being I'm just using a local copy of the library with the function removed. 
I think having to play with JVM options and read documentation makes things a lot less ergonomic.
It might be possible to put the offending function in a separate namespace?

**Comment by aboy021** [comment]
The code changes work great for me and thanks for updating the example code. Looking forward to seeing this propagated to Clojars.

**Comment by Macroz** [comment]
Thanks for the confirmation! I'll deploy to clojars when I get my keys back in order :)
