### ISSUE TITLE
Namespaces are ignored for qualified keywords.

### ISSUE THREAD

**Issue by madstap** [Macroz/tangle#4]
```
(tangle/graph->dot
 [:s3/client :datomic/client :app/server]
 [[:app/server :s3/client]
  [:app/server :datomic/client]]
 {:directed? true})
```

Result:

![repro1](https://user-images.githubusercontent.com/7657597/72686358-970d5d00-3ad2-11ea-96e9-731194e09ace.png)

Expected:

![repro2](https://user-images.githubusercontent.com/7657597/72686360-a096c500-3ad2-11ea-952e-5359b388ce32.png)

**Comment by Macroz** [comment]
I'll make a new release tomorrow! Thanks for the contribution!
